import { useQuery } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Loader2, Shield, AlertTriangle, CheckCircle, TrendingUp } from "lucide-react";
import { format } from "date-fns";
import ExecutiveSummaryReport from "@/components/reports/ExecutiveSummaryReport";
import DetailedReport from "@/components/reports/DetailedReport";
import GapAnalysisReport from "@/components/reports/GapAnalysisReport";

export default function SharedReport() {
  const urlParams = new URLSearchParams(window.location.search);
  const reportId = urlParams.get("id");

  const { data: report, isLoading } = useQuery({
    queryKey: ["shared-report", reportId],
    queryFn: async () => {
      const results = await base44.entities.ComplianceReport.filter({ id: reportId });
      return results[0];
    },
    enabled: !!reportId,
  });

  if (!reportId) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <Card className="p-12 text-center max-w-md">
          <AlertTriangle className="w-12 h-12 text-amber-400 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-slate-900 mb-2">Invalid Link</h2>
          <p className="text-slate-500">No report ID found in the URL.</p>
        </Card>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-slate-400 animate-spin" />
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <Card className="p-12 text-center max-w-md">
          <AlertTriangle className="w-12 h-12 text-amber-400 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-slate-900 mb-2">Report Not Found</h2>
          <p className="text-slate-500">This report may have been deleted or the link is invalid.</p>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <div className="bg-slate-900 text-white py-6 px-6">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-teal-500">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <div>
              <span className="text-lg font-bold">Compliance</span>
              <span className="text-lg font-light text-teal-400">Guard</span>
            </div>
          </div>
          <div className="text-right text-sm text-slate-400">
            <p>Shared Report</p>
            <p>{format(new Date(report.generated_at || report.created_date), "MMMM d, yyyy")}</p>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-8">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-slate-900">{report.title}</h1>
          <div className="flex items-center gap-3 mt-2">
            <Badge variant="outline" className="bg-slate-100 text-slate-600">
              {report.report_type?.replace(/_/g, " ")}
            </Badge>
            <span className="text-sm text-slate-500">
              Generated {format(new Date(report.generated_at || report.created_date), "MMM d, yyyy")}
            </span>
          </div>
        </div>

        <Card className="bg-white border-0 shadow-sm overflow-hidden">
          <div className="p-6">
            {report.report_type === "executive_summary" && <ExecutiveSummaryReport report={report.content} />}
            {report.report_type === "detailed" && <DetailedReport report={report.content} />}
            {report.report_type === "gap_analysis" && <GapAnalysisReport report={report.content} />}
            {report.report_type === "remediation_plan" && <DetailedReport report={report.content} />}
          </div>
        </Card>

        <p className="text-center text-xs text-slate-400 mt-6">
          This report was generated by ComplianceGuard · Confidential
        </p>
      </div>
    </div>
  );
}